SELECT * FROM employees;

SELECT EMPLOYEE_ID,
       LAST_NAME,
       JOB_ID,
       HIRE_DATE FROM employees;

SELECT ALL JOB_ID FROM employees;

SELECT  LAST_NAME || ', ' || JOB_ID "ANGAJAT SI TITLU" FROM employees;

SELECT  LAST_NAME,
        SALARY FROM EMPLOYEES WHERE SALARY > 2850;

SELECT LAST_NAME,
       DEPARTMENT_ID FROM EMPLOYEES WHERE EMPLOYEE_ID=104;

SELECT  LAST_NAME,
        SALARY FROM EMPLOYEES WHERE SALARY NOT BETWEEN 1500 AND 2850;

SELECT last_name, job_id, hire_date
FROM employees
WHERE hire_date BETWEEN '20-FEB-2014' AND '01-MAY-2015'
ORDER BY hire_date ASC;

SELECT LAST_NAME,
       DEPARTMENT_ID FROM EMPLOYEES WHERE DEPARTMENT_ID IN(10,30)
ORDER BY LAST_NAME ASC;

SELECT LAST_NAME "ANGAJAT",
       SALARY "SALARIU LUNAR" FROM EMPLOYEES WHERE DEPARTMENT_ID IN(10,30) AND SALARY > 1500 ;

SELECT LAST_NAME ,
       JOB_ID FROM EMPLOYEES WHERE MANAGER_ID IS NULL ;

SELECT LAST_NAME,
       SALARY,
       COMMISSION_PCT FROM EMPLOYEES
ORDER BY COMMISSION_PCT DESC;

SELECT LAST_NAME FROM EMPLOYEES WHERE LAST_NAME LIKE '__a%';

SELECT LAST_NAME FROM EMPLOYEES WHERE (LAST_NAME LIKE 'L%l%' OR LAST_NAME LIKE '%l%l%')
AND (DEPARTMENT_ID = 50 OR MANAGER_ID = 102);

SELECT LAST_NAME,
       JOB_ID,
       SALARY FROM EMPLOYEES WHERE (JOB_ID LIKE '%CLERK%' OR JOB_ID LIKE '%REP%') AND (SALARY != 1000 AND SALARY != 2000 AND SALARY != 3);

SELECT * FROM departments;

SELECT MAX(EMPLOYEE_ID)+1 FROM EMPLOYEES ;

SELECT DISTINCT MANAGER_ID  FROM EMPLOYEES WHERE JOB_ID = 'IT_PROG';

INSERT INTO EMPLOYEES
VALUES (
    (SELECT MAX(EMPLOYEE_ID)+1 FROM EMPLOYEES),
    'Rares',
        'IONITA',
        'RARESBOSS',
        '1.515.455.3123',
        SYSDATE,
        'IT_PROG',
        14000,
        NULL,
        103,
        60);

CREATE TABLE EMP1_PNU AS SELECT * FROM EMPLOYEES WHERE 1 = 0;

SELECT * FROM EMP0_PNU;
SELECT * FROM EMP1_PNU;
SELECT * FROM EMP2_PNU;
SELECT * FROM EMP3_PNU;

INSERT INTO EMP1_PNU
SELECT * FROM EMPLOYEES WHERE SALARY >= 10000;

DROP TABLE EMP_PNU;

CREATE TABLE EMP_PNU AS SELECT * FROM EMPLOYEES WHERE 1 = 0;
CREATE TABLE EMP1_PNU AS SELECT * FROM EMPLOYEES WHERE 1 = 0;
CREATE TABLE EMP2_PNU AS SELECT * FROM EMPLOYEES WHERE 1 = 0;
CREATE TABLE EMP3_PNU AS SELECT * FROM EMPLOYEES WHERE 1 = 0;

INSERT FIRST
    WHEN DEPARTMENT_ID = 80 THEN INTO EMP_PNU
    WHEN SALARY < 5000 THEN INTO EMP1_PNU
    WHEN SALARY BETWEEN 5000 AND 10000 THEN INTO EMP2_PNU
    WHEN SALARY > 10000 THEN INTO EMP3_PNU
SELECT * FROM EMPLOYEES;

SELECT * FROM EMP_PNU;

UPDATE EMP0_PNU
SET SALARY = SALARY * 1.05;

ROLLBACK ;

UPDATE EMP0_PNU
SET DEPARTMENT_ID =20,
    SALARY = SALARY + 1000,
    JOB_ID = 'MK_MAN'
WHERE (FIRST_NAME = 'Sean' AND LAST_NAME = 'Tucker');

UPDATE EMP0_PNU
SET JOB_ID = (SELECT JOB_ID FROM EMP0_PNU WHERE EMPLOYEE_ID = 177),
    DEPARTMENT_ID = (SELECT DEPARTMENT_ID FROM EMP0_PNU WHERE EMPLOYEE_ID = 177)
WHERE (EMPLOYEE_ID = 150);

SELECT * FROM EMP2_PNU;

DELETE FROM EMP0_PNU;
DELETE FROM EMP2_PNU WHERE COMMISSION_PCT IS NULL;

SELECT * FROM EMPLOYEES;
SELECT * FROM DEPARTMENTS;

SELECT DEPARTMENT_ID FROM DEPARTMENTS WHERE DEPARTMENT_NAME LIKE '%re%'
UNION
SELECT DEPARTMENT_ID FROM EMPLOYEES WHERE JOB_ID = 'SA_REP';


SELECT DEPARTMENT_ID FROM DEPARTMENTS
MINUS
SELECT DEPARTMENT_ID FROM EMPLOYEES;

SELECT DEPARTMENT_ID FROM DEPARTMENTS
WHERE DEPARTMENT_ID NOT IN (SELECT DEPARTMENT_ID FROM EMPLOYEES WHERE DEPARTMENT_ID IS NOT NULL);

SELECT DEPARTMENT_ID FROM DEPARTMENTS WHERE DEPARTMENT_NAME LIKE '%re%'
INTERSECT
SELECT DEPARTMENT_ID FROM EMPLOYEES WHERE JOB_ID = 'HR_REP';


SELECT LAST_NAME ,
       HIRE_DATE FROM EMPLOYEES
    WHERE HIRE_DATE > (SELECT HIRE_DATE FROM EMPLOYEES WHERE LAST_NAME = 'Li');

SELECT LAST_NAME,
       SALARY FROM EMPLOYEES
    WHERE DEPARTMENT_ID IN (SELECT DEPARTMENT_ID FROM EMPLOYEES WHERE LAST_NAME = 'Li')
AND (LAST_NAME != 'Li');

SELECT LAST_NAME,
       SALARY FROM EMPLOYEES
    WHERE MANAGER_ID IN (SELECT EMPLOYEE_ID FROM EMPLOYEES WHERE MANAGER_ID IS NULL);

SELECT DEPARTMENT_ID,
       SALARY,
       LAST_NAME FROM EMPLOYEES
WHERE (DEPARTMENT_ID, SALARY) IN (SELECT DEPARTMENT_ID,
       SALARY FROM EMPLOYEES WHERE COMMISSION_PCT IS NOT NULL);

SELECT LAST_NAME,
       SALARY FROM EMPLOYEES WHERE SALARY > ALL (SELECT SALARY FROM EMPLOYEES
WHERE JOB_ID LIKE '%CLERK%')
ORDER BY SALARY DESC;

SELECT LAST_NAME,
       SALARY,
       DEPARTMENT_ID FROM EMPLOYEES WHERE COMMISSION_PCT IS NULL
                                      AND MANAGER_ID IN (SELECT MANAGER_ID FROM EMPLOYEES WHERE COMMISSION_PCT IS NOT NULL);


SELECT * FROM (SELECT LAST_NAME,
       SALARY FROM EMPLOYEES
ORDER BY SALARY DESC) WHERE ROWNUM <= 7;

SELECT DISTINCT SALARY, LAST_NAME FROM EMPLOYEES
ORDER BY SALARY DESC;

SELECT * FROM (SELECT DISTINCT SALARY, LAST_NAME FROM EMPLOYEES
ORDER BY SALARY DESC) WHERE ROWNUM <= 7;

SELECT LAST_NAME, SALARY
FROM EMPLOYEES
WHERE SALARY IN (
    SELECT SALARY FROM (
        SELECT DISTINCT SALARY
        FROM EMPLOYEES
        ORDER BY SALARY DESC
    )
    WHERE ROWNUM <= 7
)
ORDER BY SALARY ASC;

SELECT *
FROM EMPLOYEES
WHERE SALARY = (
    SELECT MIN(SALARY) FROM (
        SELECT DISTINCT SALARY
        FROM EMPLOYEES
        ORDER BY SALARY DESC
    )
    WHERE ROWNUM <= 7
)
ORDER BY SALARY ASC;

SELECT CONCAT(FIRST_NAME, ' ') || LAST_NAME || ' CASTIGA ' || SALARY ||
       ' LUNAR DAR DORESTE ' || SALARY * 3 AS "SALARIU IDEAL"
FROM EMPLOYEES;

SELECT INITCAP(FIRST_NAME) AS "PRENUME",
       UPPER(LAST_NAME) AS "NUME",
       LENGTH(LAST_NAME) AS "LUNGIME" FROM EMPLOYEES
WHERE LAST_NAME LIKE 'J%' OR LAST_NAME LIKE 'M%' OR LAST_NAME LIKE '__A%'
ORDER BY "LUNGIME" DESC;

SELECT EMPLOYEE_ID,
       LAST_NAME,
       DEPARTMENT_ID FROM EMPLOYEES WHERE UPPER(TRIM(FIRST_NAME)) = 'STEVEN';

SELECT EMPLOYEE_ID AS "ID",
       LAST_NAME AS "NUME",
       LENGTH(LAST_NAME) AS "LUNGIME",
       INSTR (LOWER(LAST_NAME),'a') AS "POZITIE A" FROM EMPLOYEES
WHERE LAST_NAME LIKE '%e';

SELECT (SYSDATE - HIRE_DATE)/7 AS "SAPTAMANI" FROM EMPLOYEES;

SELECT FIRST_NAME,
       LAST_NAME,
       HIRE_DATE FROM EMPLOYEES
WHERE MOD(TRUNC(SYSDATE - HIRE_DATE), 7) = 0;

SELECT EMPLOYEE_ID,
       LAST_NAME,
       SALARY,
       ROUND((SALARY) + 0.15 * SALARY,2) AS "SALARIU NOU",
       ROUND(((SALARY) + 0.15 * SALARY)/100,2) AS "NUMAR SUTE" FROM EMPLOYEES
WHERE MOD(SALARY,1000) != 0;

SELECT LAST_NAME,
       SALARY,
       RPAD('$',TRUNC(SALARY/1000),'$') FROM EMPLOYEES;
       
SELECT * FROM DUAL;

SELECT TO_CHAR(SYSDATE + 30, 'MONTH DD YYYY HH24:MI:SS') AS "DATA VIITOARE"
FROM DUAL;

SELECT TO_DATE('31-12-' || TO_CHAR(SYSDATE, 'YYYY'), 'DD-MM-YYYY') - TRUNC(SYSDATE) AS "Zile ramase"
FROM dual;

SELECT LAST_NAME,
       NVL(TO_CHAR(COMMISSION_PCT),'Fara Comision') AS "COMISION" FROM EMPLOYEES;

SELECT * FROM EMPLOYEES;

SELECT LAST_NAME,
       SALARY,
       COMMISSION_PCT FROM EMPLOYEES
WHERE NVL2(COMMISSION_PCT, SALARY+COMMISSION_PCT*SALARY, SALARY) > 10000;

SELECT LAST_NAME,
       JOB_ID,
       SALARY,
       DECODE(JOB_ID,
              'IT_PROG', SALARY * 1.2,
              'SA_REP', SALARY * 1.25,
              'SA_MAN', SALARY * 1.35,
              SALARY) AS "SALARIU NEGOCIAT"
FROM EMPLOYEES;

SELECT * FROM DEPARTMENTS;

SELECT JOB_ID FROM EMPLOYEES WHERE DEPARTMENT_ID = 30;

SELECT LAST_NAME,
       DEPARTMENT_NAME FROM EMPLOYEES JOIN DEPARTMENTS
           ON (EMPLOYEES.DEPARTMENT_ID = DEPARTMENTS.DEPARTMENT_ID)
WHERE UPPER(LAST_NAME) LIKE '%A%';

SELECT * FROM LOCATIONS;
SELECT * FROM JOBS;

SELECT LAST_NAME,
       JOB_ID,
       EMPLOYEES.DEPARTMENT_ID,
       DEPARTMENT_NAME
FROM EMPLOYEES JOIN DEPARTMENTS
ON (EMPLOYEES.DEPARTMENT_ID = DEPARTMENTS.DEPARTMENT_ID)
JOIN LOCATIONS ON (DEPARTMENTS.LOCATION_ID = LOCATIONS.LOCATION_ID)
WHERE CITY = 'Oxford';

--LAB 5

SELECT EMPLOYEE_ID,
       JOB_TITLE FROM EMPLOYEES JOIN JOBS
ON (EMPLOYEES.JOB_ID = JOBS.JOB_ID)
                    WHERE SALARY > 3000 OR SALARY = (MIN_SALARY + MAX_SALARY)/2;

SELECT DEPARTMENTS.DEPARTMENT_ID,
       DEPARTMENT_NAME,
       LAST_NAME,
       JOB_TITLE
FROM DEPARTMENTS JOIN EMPLOYEES ON (DEPARTMENTS.DEPARTMENT_ID = EMPLOYEES.DEPARTMENT_ID)
JOIN JOBS ON (EMPLOYEES.JOB_ID = JOBS.JOB_ID)
WHERE LOWER(DEPARTMENT_NAME) LIKE '%ti%'
ORDER BY DEPARTMENT_NAME ASC, LAST_NAME ASC;

SELECT ANG.EMPLOYEE_ID AS "ANG#",
       ANG.LAST_NAME AS "ANGAJAT",
       SEF.EMPLOYEE_ID AS "MRG#",
       SEF.LAST_NAME AS "MANAGER"
FROM EMPLOYEES ANG
JOIN EMPLOYEES SEF ON (ANG.MANAGER_ID = SEF.EMPLOYEE_ID);

SELECT T_COLEGI.LAST_NAME,
       T_COLEGI.HIRE_DATE
FROM EMPLOYEES T_COLEGI
JOIN EMPLOYEES T_GATES ON (T_GATES.LAST_NAME = 'Gates')
WHERE T_COLEGI.HIRE_DATE > T_GATES.HIRE_DATE;

SELECT DISTINCT T1.EMPLOYEE_ID,
                T1.LAST_NAME,
                T1.DEPARTMENT_ID,
                D.DEPARTMENT_NAME    -- Luam numele din tabelul D
FROM EMPLOYEES T1
JOIN EMPLOYEES T2 ON (T1.DEPARTMENT_ID = T2.DEPARTMENT_ID)
JOIN DEPARTMENTS D ON (T1.DEPARTMENT_ID = D.DEPARTMENT_ID) -- Al 3-lea tabel legat de T1
WHERE LOWER(T2.LAST_NAME) LIKE '%t%'
  AND T1.EMPLOYEE_ID != T2.EMPLOYEE_ID
ORDER BY T1.LAST_NAME;

SELECT * FROM EMPLOYEES ORDER BY SALARY DESC;
SELECT * FROM DEPARTMENTS;
SELECT * FROM LOCATIONS;
SELECT * FROM COUNTRIES;

SELECT E1.LAST_NAME,
       E1.SALARY,
       J.JOB_TITLE,
       L.CITY,
       C.COUNTRY_NAME
FROM EMPLOYEES E1
JOIN EMPLOYEES E2 ON (E2.LAST_NAME = 'King' AND E2.FIRST_NAME= 'Steven')
JOIN JOBS J ON (E1.JOB_ID = J.JOB_ID)
JOIN DEPARTMENTS D ON (D.DEPARTMENT_ID = E1.DEPARTMENT_ID)
JOIN LOCATIONS L ON  (D.LOCATION_ID = L.LOCATION_ID)
JOIN COUNTRIES C ON (L.COUNTRY_ID = C.COUNTRY_ID)
WHERE E2.EMPLOYEE_ID = E1.MANAGER_ID;

--LAB 7

SELECT COUNT(DISTINCT manager_id) AS "Numar sefi"
FROM EMPLOYEES;

SELECT EMPLOYEE_ID, LAST_NAME 
FROM EMPLOYEES WHERE SALARY > (SELECT AVG(SALARY) FROM EMPLOYEES);

SELECT MANAGER_ID, MIN(SALARY) AS "SALARIU MINIM"  FROM EMPLOYEES
WHERE MANAGER_ID IS NOT NULL
GROUP BY MANAGER_ID HAVING MIN(SALARY)>4000
ORDER BY "SALARIU MINIM" DESC;

SELECT * FROM EMPLOYEES;

SELECT MAX(AVG(SALARY)) FROM EMPLOYEES
GROUP BY DEPARTMENT_ID;

SELECT department_id, AVG(salary)
FROM employees
GROUP BY department_id
HAVING AVG(salary) = (
    SELECT MAX(AVG(salary))
    FROM employees
    GROUP BY department_id
);

SELECT * FROM DEPARTMENTS;

SELECT DEPARTMENT_NAME, JOB_ID, SUM(SALARY) AS "SALARIU TOTAL" 
FROM EMPLOYEES JOIN DEPARTMENTS ON (EMPLOYEES.DEPARTMENT_ID = DEPARTMENTS.DEPARTMENT_ID)
WHERE EMPLOYEES.DEPARTMENT_ID>80
GROUP BY DEPARTMENT_NAME, JOB_ID ;

SELECT AVG(NVL(COMMISSION_PCT,0)) FROM EMPLOYEES;

SELECT EMPLOYEES.DEPARTMENT_ID,DEPARTMENT_NAME, COUNT( EMPLOYEES.DEPARTMENT_ID)
FROM DEPARTMENTS JOIN EMPLOYEES ON(DEPARTMENTS.DEPARTMENT_ID=EMPLOYEES.DEPARTMENT_ID)
GROUP BY  EMPLOYEES.DEPARTMENT_ID,DEPARTMENT_NAME 
HAVING COUNT( EMPLOYEES.DEPARTMENT_ID)<4;

SELECT * FROM JOBS;
SELECT * FROM EMPLOYEES;

SELECT JOBS.JOB_ID,JOB_TITLE,AVG(SALARY)
FROM JOBS JOIN EMPLOYEES ON (JOBS.JOB_ID = EMPLOYEES.JOB_ID)
GROUP BY JOBS.JOB_ID,JOB_TITLE 
HAVING AVG(SALARY) = (SELECT MIN(AVG(SALARY))
FROM EMPLOYEES GROUP BY JOB_ID);

SELECT DEPARTMENT_NAME, MIN(SALARY)
FROM DEPARTMENTS 
JOIN EMPLOYEES ON (DEPARTMENTS.DEPARTMENT_ID = EMPLOYEES.DEPARTMENT_ID)
GROUP BY DEPARTMENT_NAME HAVING AVG(SALARY) = (SELECT MAX(AVG(SALARY)) FROM EMPLOYEES
GROUP BY EMPLOYEES.DEPARTMENT_ID); 

SELECT DEPARTMENT_ID, COUNT(DEPARTMENT_ID) AS "NR_ANG", AVG(SALARY) AS "SALAR_M"
FROM EMPLOYEES
GROUP BY DEPARTMENT_ID;

SELECT DEPARTMENTS.DEPARTMENT_ID,DEPARTMENT_NAME,NR_ANG, SALAR_M ,LAST_NAME ,SALARY, JOB_TITLE
FROM DEPARTMENTS 
LEFT JOIN EMPLOYEES ON (DEPARTMENTS.department_id = EMPLOYEES.DEPARTMENT_ID)
LEFT JOIN JOBS ON (JOBS.JOB_ID = EMPLOYEES.JOB_ID)
LEFT JOIN (SELECT DEPARTMENT_ID, COUNT(DEPARTMENT_ID) AS "NR_ANG", AVG(SALARY) AS "SALAR_M"
FROM EMPLOYEES
GROUP BY DEPARTMENT_ID) TABELVIRTUAL ON (DEPARTMENTS.DEPARTMENT_ID =TABELVIRTUAL.DEPARTMENT_ID);

--LAB 8 

CREATE VIEW VIZ_EMP30_PNU AS
SELECT EMPLOYEE_ID,LAST_NAME,EMAIL,SALARY
FROM EMP_PNU
WHERE DEPARTMENT_ID = 30;

INSERT INTO VIZ_EMP30_PNU (employee_id, last_name, email, salary,HIRE_DATE, JOB_ID,DEPARTMENT_ID )
VALUES (300, 'Popescu', 'apopescu@email.com', 5000, SYSDATE, 'IT_PROG',30);

SELECT * FROM VIZ_EMP30_PNU;

CREATE OR REPLACE VIEW VIZ_EMP30_PNU AS
SELECT EMPLOYEE_ID,LAST_NAME,EMAIL,SALARY, HIRE_DATE, JOB_ID, DEPARTMENT_ID
FROM EMP_PNU
WHERE DEPARTMENT_ID = 30;

CREATE OR REPLACE VIEW VIZ_EMPSAL50_PNU AS
SELECT EMPLOYEE_ID,LAST_NAME,EMAIL,SALARY, HIRE_DATE, JOB_ID, DEPARTMENT_ID, SALARY*12 AS "SAL_ANUAL"
FROM EMP_PNU
WHERE DEPARTMENT_ID = 50;

INSERT INTO VIZ_EMPSAL50_PNU (employee_id, last_name, email, salary,HIRE_DATE, JOB_ID,DEPARTMENT_ID )
VALUES (300, 'Popescu', 'apopescu@email.com', 5000, SYSDATE, 'IT_PROG',50);

SELECT * FROM VIZ_EMPSAL50_PNU;

SELECT column_name, updatable, insertable, deletable
FROM user_updatable_columns
WHERE table_name = 'VIZ_EMPSAL50_PNU';

CREATE OR REPLACE VIEW VIZ_DEPT_SUM_PNU AS
SELECT DEPARTMENT_ID, AVG(SALARY) AS "SALARIU MEDIU"
FROM EMPLOYEES
GROUP BY DEPARTMENT_ID;

SELECT * FROM VIZ_DEPT_SUM_PNU;

SELECT * FROM LOCATIONS;
SELECT * FROM DEPARTMENTS;

CREATE OR REPLACE VIEW VIZ_SAL_PNU AS
SELECT LAST_NAME AS "NUME", 
DEPARTMENT_NAME AS "DEPARTAMENT", 
SALARY AS "SALARIU", 
CITY AS "ORAS"
FROM EMPLOYEES JOIN DEPARTMENTS ON EMPLOYEES.DEPARTMENT_ID = DEPARTMENTS.DEPARTMENT_ID
JOIN LOCATIONS ON DEPARTMENTS.LOCATION_ID = LOCATIONS.LOCATION_ID;

SELECT * FROM VIZ_SAL_PNU;

SELECT column_name, updatable, insertable, deletable
FROM user_updatable_columns
WHERE table_name = 'VIZ_SAL_PNU' ;

CREATE SEQUENCE SEQ_DEPT_PNU
START WITH 400
INCREMENT BY 10
MAXVALUE 10000
NOCYCLE
NOCACHE;

DROP SEQUENCE SEQ_DEPT_PNU;

CREATE SEQUENCE SEQ_EMP_PNU
START WITH 791
INCREMENT BY 1
MAXVALUE 8000
NOCYCLE
NOCACHE;

SELECT * FROM EMP_PNU;

UPDATE EMP_PNU
SET employee_id = SEQ_EMP_PNU.NEXTVAL;

SELECT MAX(EMPLOYEE_ID) FROM EMP_PNU;

DROP SEQUENCE SEQ_EMP_PNU;

--LAB 9

SELECT * FROM EMPLOYEES;

SELECT EMPLOYEE_ID, LAST_NAME, HIRE_DATE, SALARY, MANAGER_ID
FROM EMPLOYEES
START WITH LAST_NAME = 'Yang'
CONNECT BY PRIOR EMPLOYEE_ID = MANAGER_ID;

SELECT EMPLOYEE_ID, LAST_NAME, HIRE_DATE, SALARY, MANAGER_ID
FROM EMPLOYEES WHERE LEVEL = 3
START WITH LAST_NAME = 'Yang'
CONNECT BY PRIOR EMPLOYEE_ID = MANAGER_ID;

SELECT EMPLOYEE_ID, LAST_NAME, LEVEL, MANAGER_ID
FROM EMPLOYEES WHERE LEVEL IN (1,2,3)
CONNECT BY PRIOR MANAGER_ID = EMPLOYEE_ID;

SELECT LAST_NAME,
(SELECT COUNT(EMPLOYEE_ID) FROM EMPLOYEES
WHERE LEVEL <> 1
CONNECT BY PRIOR EMPLOYEE_ID = MANAGER_ID) AS "NUMAR_SUBALTERNI"
FROM EMPLOYEES;

SELECT e.last_name, e.employee_id,
       (SELECT COUNT(*)
        FROM employees
        START WITH manager_id = e.employee_id
        CONNECT BY PRIOR employee_id = manager_id) AS numar_subalterni
FROM employees e;

--LAB 9

SELECT DEPARTMENT_NAME, JOB_TITLE, AVG(SALARY),GROUPING(DEPARTMENT_NAME),GROUPING(JOB_TITLE)
FROM DEPARTMENTS
JOIN EMPLOYEES ON DEPARTMENTS.DEPARTMENT_ID = EMPLOYEES.DEPARTMENT_ID
JOIN JOBS ON JOBS.JOB_ID = EMPLOYEES.JOB_ID
GROUP BY ROLLUP (DEPARTMENT_NAME, JOB_TITLE);

SELECT 
    D.department_name, 
    J.job_title, 
    AVG(E.salary),
    CASE 
        WHEN GROUPING(D.department_name) = 0 AND GROUPING(J.JOB_TITLE) = 0 THEN 'DepJob'
        WHEN GROUPING(D.department_name) = 0 THEN 'Dep'
        WHEN GROUPING(J.job_title) = 0       THEN 'Job'
        ELSE 'Niciuna'
    END AS indicator_agregare
FROM DEPARTMENTS D
JOIN EMPLOYEES E ON D.DEPARTMENT_ID = E.DEPARTMENT_ID
JOIN JOBS J ON J.JOB_ID = E.JOB_ID
GROUP BY CUBE (D.DEPARTMENT_NAME, J.JOB_TITLE);

SELECT * FROM DEPARTMENTS;

SELECT DEPARTMENT_NAME, JOB_TITLE, EMPLOYEES.MANAGER_ID, MAX(SALARY), SUM(SALARY)
FROM DEPARTMENTS
JOIN EMPLOYEES ON DEPARTMENTS.DEPARTMENT_ID = EMPLOYEES.DEPARTMENT_ID
JOIN JOBS ON JOBS.JOB_ID = EMPLOYEES.JOB_ID
GROUP BY GROUPING SETS ( (DEPARTMENT_NAME, JOB_TITLE),
(JOB_TITLE,EMPLOYEES.MANAGER_ID), ( ) );

SELECT TO_CHAR(HIRE_DATE, 'dd') FROM EMPLOYEES;
